# Generated by Django 5.1.3 on 2024-11-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='orgin',
            new_name='origin',
        ),
    ]
